spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        # Có thể để Spring tự suy ra dialect, nhưng khai báo rõ để chắc chắn:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
      jakarta:
        persistence:
          validation:
            mode: none

  datasource:
    url: jdbc:postgresql://localhost:5432/socialMediaApp
    username: postgres
    password: "1"
    # driver-class-name: org.postgresql.Driver  # Thường không cần khai báo

  sql:
    init:
      mode: never

  cloud:
    gateway:
      routes:
        - id: socialmedia
          uri: http://localhost:8080
          predicates:
            - Cookie=mycookie,mycookievalue

  cache:
    type: redis

  redis:
    host: localhost
    port: 6379

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration

jwt:
  secret: "mysupersecretkeymysupersecretkeymysupersecretkey"

logging:
  level:
    org.springframework.cache: DEBUG
