spring.application.name=like-service
# ========== MONGODB ==========
spring.data.mongodb.uri=mongodb://localhost:27017/like-service-db

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=post-service-db
spring.main.web-application-type=servlet

#app.jwt.secret=Ab17031991@#icomefromHanoicityandIloveyouWhatdoyoumeanAhihihi
#app.jwt.expiration=8640000000
#app.jwt.refresh-expiration=2592000000
#
#quiz.admin.email=admin@gmail.com
#quiz.admin.password=A123456a@
server.port= 8084